### PR TITLE
Issues whiles connecting read replicas behind HAProxy

### PR DESCRIPTION
**Pull request by vishaltelangre**

### CODE REVIEW

**Comment by vishaltelangre** [comment]
cc: @prathamesh-sonpatki @scottkf

**Comment by prathamesh-sonpatki** [comment]
@vishaltelangre See if we can use https://github.com/ruby-concurrency/concurrent-ruby to handle threads? I am not sure if it is useful in this case or not but just posting it here.

**Comment by vishaltelangre** [comment]
Thanks. I will take a look at that library.

**Comment by prathamesh-sonpatki** [comment]
Lol got a notification for this 😄

**Comment by vishaltelangre** [comment]
Found that it was unattended for a long time! 😂

**Pull request closed without merging**
